#!/bin/bash
# Dadi's Care Hub - Automated Deployment Script
# Usage: ./deploy.sh [PROJECT_ID]

PROJECT_ID=$1

if [ -z "$PROJECT_ID" ]; then
  echo "Error: Please provide your Google Cloud Project ID."
  echo "Usage: ./deploy.sh [PROJECT_ID]"
  exit 1
fi

echo "========================================"
echo "Deploying Backend to Google Cloud Run..."
echo "========================================"
cd backend

# Required: Ensure backend has a Dockerfile (Add one if missing)
if [ ! -f Dockerfile ]; then
    echo "Creating basic Dockerfile for Express backend..."
    cat <<EOF > Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
ENV PORT=8080
EXPOSE 8080
CMD [ "npm", "start" ]
EOF
fi

# Build and Push container to GCR
gcloud builds submit --tag gcr.io/$PROJECT_ID/dadis-care-backend
# Deploy to Cloud Run
gcloud run deploy dadis-care-backend \
  --image gcr.io/$PROJECT_ID/dadis-care-backend \
  --platform managed \
  --region us-central1 \
  --allow-unauthenticated \
  --set-env-vars="GEMINI_API_KEY=secrets.GEMINI_API_KEY"

cd ..

echo "========================================"
echo "Deploying Frontend to Firebase Hosting..."
echo "========================================"
cd frontend

# Build Vite React app
npm run build

# Deploy to Firebase Hosting
firebase deploy --only hosting --project $PROJECT_ID

echo "========================================"
echo "Deployment Complete!"
echo "Cloud Run URL will be generated by GCP."
